// <auto-generated/>
#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "1.0"
#define szVerMajorMinorBuildRev "1.0.4798.23908"
#define rmj	1
#define rmm	0
#define rbd	4798
#define rev	23908

#endif
