// <auto-generated/>
#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "1.0"
#define szVerMajorMinorBuildRev "1.0.4820.39346"
#define rmj	1
#define rmm	0
#define rbd	4820
#define rev	39346

#endif
