// <auto-generated/>
#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "1.0"
#define szVerMajorMinorBuildRev "1.0.5505.41129"
#define rmj	1
#define rmm	0
#define rbd	5505
#define rev	41129

#endif
