// <auto-generated/>
#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "1.0"
#define szVerMajorMinorBuildRev "1.0.6401.181"
#define rmj	1
#define rmm	0
#define rbd	6401
#define rev	181

#endif
