// <auto-generated/>
#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "3.10"
#define szVerMajorMinorBuildRev "3.10.6401.181"
#define rmj	3
#define rmm	10
#define rbd	6401
#define rev	181
#define szVerName	"BalExtensionExt Release"

#endif
