// <auto-generated/>
#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "3.7"
#define szVerMajorMinorBuildRev "3.7.4798.23869"
#define rmj	3
#define rmm	7
#define rbd	4798
#define rev	23869
#define szVerName	"BalExtensionExt Release"

#endif
