// <auto-generated/>
#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "1.0"
#define szVerMajorMinorBuildRev "1.0.4826.14231"
#define rmj	1
#define rmm	0
#define rbd	4826
#define rev	14231

#endif
